spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/heima?serverTimezone=GMT%2B8
    username: root
    password: root
  redis:
    host: 192.168.190.128

  rabbitmq:
    virtual-host: /leyou
    host: 127.0.0.1
    username: leyou
    password: leyou
server:
  port: 8085
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
mybatis:
  type-aliases-package: com.leyou.user.pojo
