server:
  port: 8084
spring:
  application:
    name: goods-web
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
  rabbitmq:
    virtual-host: /leyou
    host: 127.0.0.1
    username: leyou
    password: leyou
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5